/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CourseCategory = IDL.Variant({
  'data' : IDL.Null,
  'design' : IDL.Null,
  'cybersecurity' : IDL.Null,
  'technology' : IDL.Null,
  'business' : IDL.Null,
});
export const Job = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'category' : CourseCategory,
  'requiredSkills' : IDL.Vec(IDL.Text),
});
export const LearningResource = IDL.Record({
  'url' : IDL.Text,
  'provider' : IDL.Text,
  'estimatedHours' : IDL.Nat,
  'courseName' : IDL.Text,
});
export const StudentJobMatch = IDL.Record({
  'job' : Job,
  'matchPercent' : IDL.Nat,
  'missingResources' : IDL.Vec(LearningResource),
  'missingSkills' : IDL.Vec(IDL.Text),
});
export const StudentProfile = IDL.Record({
  'name' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInfo' : IDL.Func([], [IDL.Text], ['query']),
  'getJobMatchingPercent' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getJobsByPercent' : IDL.Func([], [IDL.Vec(StudentJobMatch)], []),
  'getStudentProfile' : IDL.Func([], [StudentProfile], ['query']),
  'getStudentSkills' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveJob' : IDL.Func([Job], [], []),
  'saveProfile' : IDL.Func([StudentProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CourseCategory = IDL.Variant({
    'data' : IDL.Null,
    'design' : IDL.Null,
    'cybersecurity' : IDL.Null,
    'technology' : IDL.Null,
    'business' : IDL.Null,
  });
  const Job = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'category' : CourseCategory,
    'requiredSkills' : IDL.Vec(IDL.Text),
  });
  const LearningResource = IDL.Record({
    'url' : IDL.Text,
    'provider' : IDL.Text,
    'estimatedHours' : IDL.Nat,
    'courseName' : IDL.Text,
  });
  const StudentJobMatch = IDL.Record({
    'job' : Job,
    'matchPercent' : IDL.Nat,
    'missingResources' : IDL.Vec(LearningResource),
    'missingSkills' : IDL.Vec(IDL.Text),
  });
  const StudentProfile = IDL.Record({
    'name' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInfo' : IDL.Func([], [IDL.Text], ['query']),
    'getJobMatchingPercent' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getJobsByPercent' : IDL.Func([], [IDL.Vec(StudentJobMatch)], []),
    'getStudentProfile' : IDL.Func([], [StudentProfile], ['query']),
    'getStudentSkills' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveJob' : IDL.Func([Job], [], []),
    'saveProfile' : IDL.Func([StudentProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };