/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CourseCategory = { 'data' : null } |
  { 'design' : null } |
  { 'cybersecurity' : null } |
  { 'technology' : null } |
  { 'business' : null };
export interface Job {
  'title' : string,
  'description' : string,
  'company' : string,
  'category' : CourseCategory,
  'requiredSkills' : Array<string>,
}
export interface LearningResource {
  'url' : string,
  'provider' : string,
  'estimatedHours' : bigint,
  'courseName' : string,
}
export interface StudentJobMatch {
  'job' : Job,
  'matchPercent' : bigint,
  'missingResources' : Array<LearningResource>,
  'missingSkills' : Array<string>,
}
export interface StudentProfile { 'name' : string, 'skills' : Array<string> }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInfo' : ActorMethod<[], string>,
  'getJobMatchingPercent' : ActorMethod<[string], bigint>,
  'getJobsByPercent' : ActorMethod<[], Array<StudentJobMatch>>,
  'getStudentProfile' : ActorMethod<[], StudentProfile>,
  'getStudentSkills' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveJob' : ActorMethod<[Job], undefined>,
  'saveProfile' : ActorMethod<[StudentProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];